--criando a tabela de clientes
CREATE TABLE CLIENTE(
	ID				UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME			VARCHAR(100)		NOT NULL,
	CPF				VARCHAR(11)			NOT NULL,
	DATANASCIMENTO	DATE				NOT NULL)
GO


--inseriendo cliente
INSERT INTO CLIENTE(ID, NOME, CPF, DATANASCIMENTO)
VALUES(NEWID(), 'Lucas Moraes', '12345678998', '1995-02-26')
GO

INSERT INTO CLIENTE(ID, NOME, CPF, DATANASCIMENTO)
VALUES(NEWID(), 'Ana Paula', '00123456789', '2000-01-20')
GO

--consultando os clientes
SELECT * FROM CLIENTE
GO